{% set name = "gvisor" %}
{% set version = "20211101.0" %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/{{ name }}/archive/release-{{ version }}.tar.gz
  sha256: 400b714d1350c84ad0a2926805ec89afb8b2d27b51fbe24d321c170a7ba45925
  patches:
    - syscalls_rmv_boottime.patch   # CLOCK_BOOTTIME is not a defined variable in time.h header of C Library in conda-forge. Remove from source code.

build:
  number: 0
  skip: true  # [osx or win]
  ignore_run_exports:
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('cgo') }}
    - git
    - bazel

test:
  commands:
    - runsc help

about:
  home: https://gvisor.dev
  license: Apache-2.0
  license_file: LICENSE
  summary: Container Runtime Sandbox
  doc_url: https://gvisor.dev/docs
  dev_url: https://github.com/google/gvisor

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
